language: node_js
node_js:
  - "0.11"
  - "0.10"
branches:
  only:
  - master
before_install: gem install compass
install: 
  - npm install -g bower
  - npm install -g gulp
  - cd $TRAVIS_BUILD_DIR/admin
  - npm install
  - bower install
  - cd $TRAVIS_BUILD_DIR/portal
  - npm install
  - bower install
script: 
  - cd $TRAVIS_BUILD_DIR/admin
  - gulp
  - cd $TRAVIS_BUILD_DIR/portal
  - gulp
notifications:
  email:
    - lzy7750015@qq.com