language: node_js
node_js:
  - "0.11"
  - "0.10"
branches:
  only:
  - master
before_install: gem install compass
install: 
  - npm install -g bower
  - npm install -g gulp
  - npm install
  - bower install
script: gulp
notifications:
  email:
    - lzy7750015@qq.com